# Generated by Django 4.1.5 on 2023-01-06 15:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trench", "0004_alter_mfamethod_id_mfamethod_unique_user_is_primary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MFAUsedCode",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("code", models.CharField(max_length=6, verbose_name="code")),
                (
                    "used_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 1, 6, 15, 26, 17, 535559, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="used_at",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expires_at")),
                ("method", models.CharField(max_length=255, verbose_name="method")),
            ],
            options={
                "verbose_name": "MFA Last Used Code",
                "verbose_name_plural": "MFA Last Used Codes",
            },
        ),
        migrations.RemoveConstraint(
            model_name="mfamethod",
            name="primary_is_active",
        ),
        migrations.AlterField(
            model_name="mfamethod",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="mfamethod",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("is_primary", True), ("is_active", True)),
                    ("is_primary", False),
                    _connector="OR",
                ),
                name="primary_is_active",
            ),
        ),
        migrations.AddField(
            model_name="mfausedcode",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mfa_used_codes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
