# Generated by Django 4.1.7 on 2023-03-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trench", "0004_alter_mfamethod_id_mfamethod_unique_user_is_primary_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mfamethod",
            name="primary_is_active",
        ),
        migrations.AlterField(
            model_name="mfamethod",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="mfamethod",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_user_method_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="mfamethod",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("is_primary", True), ("is_active", True)),
                    ("is_primary", False),
                    _connector="OR",
                ),
                name="primary_is_active",
            ),
        ),
    ]
