# Generated by Django 4.1.5 on 2023-03-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trench", "0005_remove_mfamethod_primary_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mfamethod",
            name="code_generated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="code generated at"
            ),
        ),
        migrations.AddField(
            model_name="mfamethod",
            name="counter",
            field=models.PositiveIntegerField(default=0, verbose_name="counter"),
        ),
    ]
