# Generated by Django 4.1.5 on 2023-01-10 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0004_alter_user_first_name_alter_user_id_and_more"),
        ("trench", "0006_alter_mfausedcode_used_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="MFABackupCodes",
            fields=[
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="mfa_backup_codes",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                ("_values", models.TextField(verbose_name="backup codes")),
            ],
            options={
                "verbose_name": "MFA Backup Code",
                "verbose_name_plural": "MFA Backup Codes",
            },
        ),
        migrations.RemoveField(
            model_name="mfamethod",
            name="_backup_codes",
        ),
    ]
